agent:
  # HCP Authentication
  hcp:
    client_id: ${HCP_CLIENT_ID}
    client_secret: ${HCP_CLIENT_SECRET}
    organization_id: ${HCP_ORGANIZATION_ID}
    project_id: ${HCP_PROJECT_ID}
    app_name: ${HCP_APP_NAME}

  # Agent behavior settings
  settings:
    exit_on_retry_failure: false  # Whether to exit if max retries reached
    retry:
      max_attempts: 3        # Maximum retry attempts
      backoff_initial: 1s    # Initial backoff duration
      backoff_max: 30s       # Maximum backoff duration
      jitter: true          # Add randomness to backoff
    cache:
      enabled: true         # Enable secret caching
      ttl: 86400s           # Cache TTL (24 hours as fallback)
      version_check: true   # Enable version checking
      version_check_interval: 10s  # Check versions more frequently (every 10 seconds)
      batch_api: true       # Enable batch API for efficient multi-secret retrieval

  # Logging configuration
  logging:
    level: info  # debug, info, warn, error
    format: text # text or json
    mask_secrets: true

  # Templates to render
  templates:
    - source: "env.tmpl"
      destination: "secrets.env"
      error_on_missing_key: true
      create_directories: true
      permissions: "0600" 