hcp_auth:
  client_id: ${HCP_CLIENT_ID}
  client_secret: ${HCP_CLIENT_SECRET}
  organization_id: ${HCP_ORGANIZATION_ID}
  project_id: ${HCP_PROJECT_ID}
  app_name: ${HCP_APP_NAME}

agent:
  render_interval: 5s
  no_exit_on_retry: false
  retry:
    max_attempts: 3
    initial_backoff: 1s
    max_backoff: 30s
    use_jitter: true
  cache:
    enabled: true
    ttl: 5m

logging:
  level: info
  format: text
  mask_secrets: true

templates:
  - source: "env.tmpl"
    destination: "secrets.env"
    error_on_missing_keys: true
    create_dir: true
    file_perms: 0600 