name: Build

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: [amd64, arm64]
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      env:
        GOOS: linux
        GOARCH: ${{ matrix.goarch }}
      run: |
        go build -v -o vault-secret-agent_${{ matrix.goarch }} ./...

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: vault-secret-agent_${{ matrix.goarch }}
        path: vault-secret-agent_${{ matrix.goarch }}
        retention-days: 90